apiVersion: v1
kind: Service
metadata:
  name: {{ include "workadventure.fullname" . }}-play
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    role: play
spec:
  type: {{ .Values.play.service.type }}
  ports:
    - port: {{ .Values.play.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.play.service.wsPort }}
      targetPort: {{ .Values.play.service.wsPort }}
      protocol: TCP
      name: ws
  selector:
    {{- include "workadventure.selectorLabels" . | nindent 4 }}
    role: play
